import os
import subprocess
import signal

def kill_malware_process():
    """
    Reads the 'malware.pid' file generated by the simulator
    and physically terminates that process ID.
    """
    try:
        # Check if the simulator registered its ID
        if os.path.exists("malware.pid"):
            with open("malware.pid", "r") as f:
                pid = int(f.read().strip())
            
            print(f"🔫 ASSASSIN ACTIVATED: Terminating Process {pid}...")
            
            # Send the Kill Signal (SIGTERM is standard, works on Windows/Linux)
            os.kill(pid, signal.SIGTERM) 
            
            # Clean up the PID file so we don't try to kill a ghost later
            try: os.remove("malware.pid")
            except: pass
            
            return True
        else:
            print("⚠️ No Active Malware PID found to kill.")
            return False
            
    except Exception as e:
        print(f"⚠️ Assassin Failed: {e}")
        return False

def sever_connection():
    """
    QUARANTINE PROTOCOL:
    Only cuts the Network adapter to stop data exfiltration.
    Does NOT kill the process (we let the user do that).
    """
    print("⚔️ AEGIS CONTAINMENT PROTOCOL STARTED...")
    try:
        # Windows Command to disable Wi-Fi adapter
        subprocess.run('netsh interface set interface "Wi-Fi" admin=disable', shell=True)
        print("✂️  NETWORK SEVERED (Wi-Fi Disabled)")
    except Exception as e:
        print(f"⚠️ Could not disable Wi-Fi: {e}")

def restore_connection():
    """Restores Internet Access."""
    print("🔌 RESTORING NETWORK UPLINK...")
    try:
        subprocess.run('netsh interface set interface "Wi-Fi" admin=enable', shell=True)
    except Exception as e:
        print(f"⚠️ Could not restore Wi-Fi: {e}")